# Generated by Django 3.2.4 on 2021-09-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/child_category/icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Child Catagories',
            },
        ),
        migrations.CreateModel(
            name='GrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/grand_category/thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Grand Categories',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='media/parent_category/icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grand_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.grandcategory')),
            ],
            options={
                'verbose_name_plural': 'Parent Catagories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('code', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('sub_title', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('sold_Times', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='media/product/thumbnail')),
                ('is_Active', models.BooleanField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestSeller', models.BooleanField(default=False)),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.childcategory')),
                ('grand_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.grandcategory')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.parentcategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SubAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/productSliderImage/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_slider_images', to='product.product')),
                ('sub_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subattribute')),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('One Time', 'One Time'), ('Multiple Time', 'Multiple Time')], max_length=50)),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='childcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.parentcategory'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='sub_attribute',
            field=models.ManyToManyField(related_name='sub_property', to='product.SubAttribute'),
        ),
    ]
