# Generated by Django 3.2.4 on 2022-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220108_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Talha Sarwar', max_length=300, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
