# Generated by Django 3.2.4 on 2021-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/home/logo')),
                ('banner_Image', models.ImageField(blank=True, null=True, upload_to='media/home/banner')),
                ('bestseller_product_title', models.CharField(max_length=120)),
                ('bestseller_product_title_message', models.CharField(max_length=120)),
                ('bestseller_product_title_description', models.CharField(max_length=120)),
                ('featured_product_title', models.CharField(max_length=120)),
                ('featured_product_title_message', models.CharField(max_length=120)),
                ('featured_product_title_description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='media/home/Slider')),
            ],
            options={
                'verbose_name_plural': 'Home Page Slider',
            },
        ),
    ]
