# Generated by Django 3.2.4 on 2022-01-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220108_1324'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/home/logo'),
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_title', models.CharField(max_length=1000)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.grandcategory')),
                ('home', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('home', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(max_length=1000)),
                ('facebook_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('office_address', models.CharField(max_length=2000)),
                ('phone_no', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('home', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.homepagecontent')),
            ],
        ),
    ]
